### ISSUE TITLE
[bug] in league, switching to the default order while hiding already fought opponents results in an incorrect view

### ISSUE THREAD

**Issue by TheGlider0** [45026831/hh-plus-plus#23]
When hiding the already fought opponents and then switching to the default order, the view is incorrect. Specifically, if I have N unfought players it simply shows the last N players (from some different order) and also incorrectly presents them as not fought in the "Ch." column (probably simply doesn't update the column). See attached images. In the first case I toggled the "Ch." column and still have 63 unfought players so it shows the last 63 players in the ranking order. The second case is the same except I toggled the "Lvl." column.

Hentai Heroes++ BDSM version | 0.33.6

![Untitled](https://user-images.githubusercontent.com/90114177/132927916-577896ae-4290-4284-ad98-5eab80a97cba.png)
![Untitled2](https://user-images.githubusercontent.com/90114177/132928269-a4b4d5c7-c579-4503-99c4-8850d304ec03.png)

**Comment by 45026831** [comment]
Fixed in 0.33.8 (b58d6d6)
