### ISSUE TITLE
[feature] Add breadcrumbs to villain perform page

### ISSUE THREAD

**Issue by Kitowski** [45026831/hh-plus-plus#39]
When stepping from "Adventure" through to the villain performance/fight, there is a series of links that would look like:
Town > Adventure > Digisekai 
These are found near the upper left of the screen.
These links do not carry through to show on the performance screen.
Since we can jump directly to the performance screen from the menu added on the combativity bar, it would be nice to be able to "step down" to the adventure world that would call us there (or even further).

Propose to add something on the perform screen that would look like:
Town> Adventure > Digisekai > Pandora Witch
where "Pandora Witch" is not a selectable link (consistent with prior levels)
Digisekai links to https://www.hentaiheroes.com/world/13
Adventure links to https://www.hentaiheroes.com/map.html
Town links to https://www.hentaiheroes.com/home.html

**Comment by 45026831** [comment]
Done in v1.6.0
