### ISSUE TITLE
[bug] Currently buyable stock shows ymen not kobans

### ISSUE THREAD

**Issue by Kitowski** [45026831/hh-plus-plus#40]
On the harem page to the lower left there is an icon you can click to show a "Harem Stats" page

If you have mythic books and/or mythic gifts in the market, these show up as ymen purchase items instead of koban purchase items for "Currently buyable stock"

**Comment by 45026831** [comment]
Known bug, and fix is already in progress in the v1.0.0 branch. Will leave this open for tracking.

**Comment by 45026831** [comment]
Done in 1.0.0
