### ISSUE TITLE
[bug] Market stopped showing girls and extra buttons

### ISSUE THREAD

**Issue by TheGlider0** [45026831/hh-plus-plus#42]
On girl XP and affection sections in the market no girls are shown.
On equip section the extra buttons (sort and block selling buttons) are not shown.

![Screenshot 2021-11-22 223429](https://user-images.githubusercontent.com/90114177/142932346-bfd4c2ec-e1cb-45e2-b2e6-db958fd52768.png)

![Screenshot 2021-11-22 223459](https://user-images.githubusercontent.com/90114177/142932362-3816bc6e-d424-45be-87af-d2e52c1481b5.png)

 - Browser Chrome
 - Version 0.37.26
 - Game HH
 - Platform Nutaku

**Comment by TheGlider0** [comment]
Update: It all returns to normal after selecting a filter once. Then it stays good even if the filter is removed. It's still probably not the intended behavior so I'll leave the issue open.

**Comment by 45026831** [comment]
Fixed in v0.37.27 (61571fc)
