### ISSUE TITLE
[bug] Adventure breadcrumbs are incorrectly moved in front of menu

### ISSUE THREAD

**Issue by Kitowski** [45026831/hh-plus-plus#45]
Breadcrumbs for adventure are moved in front of the menu displayed by hamburger menu button.

**To Reproduce (tested on Chrome)**
Go to adventure
Select the hamburger menu
You will still see the breadcrumbs

Turn off the script and compare results.

**Comment by 45026831** [comment]
Fixed in v0.37.36 (bc6cf07)
