### ISSUE TITLE
[bug] Dragging buyable items in the market causing game to being interrupted and stop working (v1.0.0)

### ISSUE THREAD

**Issue by Dogurasu53** [45026831/hh-plus-plus#48]
**Describe the bug**
Something with the Equips Filter at the Market Module from v1.0.0 is causing the game to slow down and being asked to interrupt the game when you drag any buyable item that isn't an equipment from the market, I assume it's something associated with being able to sell the item if you drag an item from your inventory to the buyable section of the market to sell. It also causes the what you see in the screenshot to happen to your inventory.

**To Reproduce**
1. Go to the Market
2. Click on the Boosters, Books or Gifts Tab
3. Drag any buyable item

**Expected behavior**
Being able to buy by dragging the item from the market to your inventory or not being able to drag buyable items at all

**Screenshots**
![image](https://user-images.githubusercontent.com/31224112/152251339-bd4ffb50-5544-431f-821b-01ed4352057c.png)

**Version info:**
 - Browser: Mozilla Firefox
 - Version: HH++ v1.0.0
 - Game: HH
 - Platform: Nutaku

**Aditional Info:**
There was no other scripts activated at the same time and it only happens when the Equip Filter at the Market Module is activated, didn't test if it also happens with other browsers, and on mobile

**Comment by Dogurasu53** [comment]
Update: it also slows down and asks to interrupt the game when clicking on a booster in the resource bars at the top to go to the boosters page

**Comment by 45026831** [comment]
Fixed
