### ISSUE TITLE
[feature] Add option to turn on countdown on the resource bars.

### ISSUE THREAD

**Issue by SeveralCats** [45026831/hh-plus-plus#49]
![2134](https://user-images.githubusercontent.com/98997195/152464352-a111aaa2-05ad-43af-a005-7bb9bc9400ed.png)
![213](https://user-images.githubusercontent.com/98997195/152464361-1fab6c2c-bbe0-4f21-a429-f686637c7142.png)

**Comment by 45026831** [comment]
Done in 1.0.1 (ad7ea54)
