### ISSUE TITLE
[bug] Season's rewards

### ISSUE THREAD

**Issue by UncleBob800** [45026831/hh-plus-plus#57]
Found a bug with season's rewards in version 1.6.7
![image](https://user-images.githubusercontent.com/86453893/156093971-b706ad16-2971-4ed7-963c-02a7a791a6b1.png)

**Comment by UncleBob800** [comment]
A very strange phenomenon. I refreshed the page several times and the problem did not disappear. After a while, everything returned to normal and began to display correctly. Most likely, the page did not have time to update in the cache (the script was updated half an hour ago) and a conflict arose. If anyone encounters a similar problem, then try pressing Ctrl + F5 (refresh the page with clearing the cache), go to the main page, and then go back to the season section.

**Comment by 45026831** [comment]
This should be fixed in v1.6.8, can you please confirm?

**Comment by UncleBob800** [comment]
Yep, bug is gone. 😉👍
