### ISSUE TITLE
[bug] onAjaxResponse() crash if ajax response doesn't contains data

### ISSUE THREAD

**Issue by DevilPF** [45026831/hh-plus-plus#58]
**Describe the bug**
onAjaxResponse() crash with "Uncaught TypeError: Cannot read properties of undefined (reading 'search')" if ajax response doesn't contains data. E.g. on response from another script it the response is not json.

**To Reproduce**
1. open console
2. do Ajax request - e.g. $.ajax({dataType: 'json', url: "https://some.url" })
3. See error

**Expected behavior**
Not throw an exception.

**Screenshots**

**Version info (please complete the following information):**
 - Browser chrome
 - Version 98
 - Game HH/CxH
 - Platform HH.com, CxH.com

**Additional context**

It should be sufficient to modify onAjaxResponse in src\common\Helpers.js 
instead of "~a.data.search(s)" test it first - "a.data && ~a.data.search(s)"

**Comment by 45026831** [comment]
Fixed in v1.7.6
