### ISSUE TITLE
Provide dominance bonuses in league simulator

### ISSUE THREAD

**Issue by hhanon** [45026831/hh-plus-plus#63]
**Is your feature request related to a problem? Please describe.**
I am playing around with your league simulator and would like to use `player` and `opponent` dominance bonuses:
https://github.com/45026831/hh-plus-plus/blob/3fa5443819ff767127a3100c35e47c56828946fb/src/modules/BattleSimulatorModule/League.js#L89-L103

**Describe the solution you'd like**
Provide the respective dominance bonuses as part of the `player` and `opponent` objects (or alternatively the player/opponent elements, as one can use the helper to derive the bonuses). I understand that those are not really needed for subsequent calculations, but given the amazing extensibility support you have provided and the effort that you have put into handling all corner cases, it will be great to make it available to others.

**Describe alternatives you've considered**
I can duplicate the code, but that seems ughh...

**Additional context**
Thanks a bunch for the amazing script!

**Comment by 45026831** [comment]
Done in v1.7.10. In the output of `League.extract()`, `player` and `opponent` now both have `bonuses.dominance` that contains the 3 dominance bonus values and `theme` that lists the theme elements (empty for balanced). Does that cover everything you needed?

**Comment by hhanon** [comment]
That's perfect! Thanks a lot for the quick solution!
