### ISSUE TITLE
Additional elements to hide

### ISSUE THREAD

**Issue by coraphise** [45026831/hh-plus-plus#68]
I love this script and I wish I'd known about it sooner; thank you all for your work on the script!

My request:
I find the links to Follow us, Comix Heroes, Harem Heroes, or Gay Harem annoying. Is it possible to add an option that would hide these?

I'd also like options to hide the Treasure Chest (bundles/special offers), monthly card, mailbox (updates), and the Thank You in Harem Heroes. I don't see that in Comix Heroes and don't play Gay Harem, so I'm not sure if it's there.

I didn't see this listed in open issues, I hope I didn't miss it if it was there.

Thank you for considering!

**Comment by 45026831** [comment]
The companion script Style Tweaks https://github.com/45026831/hh-style-tweaks has the option to hide the game links.

The rest are mostly out of the way in the corner and the mailbox is important, so no plans to hide those for now.

**Comment by coraphise** [comment]
Hi, I didn't realize there was a comment. Thank you for sharing the secondary script! While it did modify the game menu (it's smaller, so much better!!), I don't see how to hide the game links.

I see where it is in the code and will try to pick it apart tonight.

Thank you again for sharing this!

**Comment by 45026831** [comment]
It's a setting that's off be default, so you'll need to switch it on in the settings

**Comment by coraphise** [comment]
I figured out this script added a secondary settings options under H++/C++ settings for Style Tweaks, and found the settings there.

Thank you again!!
