### ISSUE TITLE
Uncapped/capped filter on league/season team edit

### ISSUE THREAD

**Issue by sliqguy** [45026831/hh-plus-plus#72]
Add the "uncapped/capped" filter from the market filter to the league/season team building filters.  This will conveniently allow the player to select a girl who is not capped to be on the team in seasons and earn XP from a win in seasons.  There is an open space in the bottom right corner of the filter to add this filter.

**Comment by 45026831** [comment]
Unfortunately, unlike the market, the team selection page does not provide level cap information. So to do this would not be straightforward.

**Comment by 45026831** [comment]
Thanks to @rena-jp, this is now in v1.20.2
