### ISSUE TITLE
Little bug with Market filters.

### ISSUE THREAD

**Issue by UncleBob800** [45026831/hh-plus-plus#74]
Normal mode:
![image](https://user-images.githubusercontent.com/86453893/176895524-eb041f07-9a1c-416c-bb4a-2f5fba72d77f.png)
Mobile mode:
![image](https://user-images.githubusercontent.com/86453893/176895673-9b00192b-3b78-44af-afaf-0db07ef121c3.png)

Found a solution: need remove `position:relative` in the line 202.
![image](https://user-images.githubusercontent.com/86453893/176896085-56cac653-9480-406b-a65f-91f9e74b3411.png)
    🔽🔽🔽
![image](https://user-images.githubusercontent.com/86453893/176896149-55bbd0c6-8782-493d-bffd-c00e7403d1c1.png)

![image](https://user-images.githubusercontent.com/86453893/176896493-d09e0157-92ca-4567-bc8d-6055e96d6b77.png)
![image](https://user-images.githubusercontent.com/86453893/176896614-6af58254-a735-4cc4-a1e7-30c48672de1d.png)

**Comment by 45026831** [comment]
Fixed in v1.18.1
