### ISSUE TITLE
LeaderboardFixModule is out of date

### ISSUE THREAD

**Issue by rena-jp** [45026831/hh-plus-plus#79]
LeaderboardFixModule (Fix Season and PoV leaderboards) has problems.

1. Does not support PoG.
2. Opening PoV Leaderboard after PoG Leaderboard, clones PoG rank to PoV, because there are two #leaderboard_list.

The purpose of LeaderboardFixModule is to always display the player's rank at the bottom.
I think style tweak is better.

```
#seasons_main_container .leaderboard_row[style] {
    position: fixed;
    bottom: 30px;
    width: 904px;
}

.potions-paths-background-panel .leaderboard_row.hero-row {
    position: fixed;
    bottom: 16px;
    width: 910px;
}
```

**Comment by 45026831** [comment]
Well we definitely want it cloned to see it in context as well as on its own. Ideally, it would be sticky and then flow with the table when in view, but that's arguably more complicated than it's worth.

**Comment by rena-jp** [comment]
Hmm, if it's the kind of thing, we should fix Pantheon leaderboard as well.
